name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: lab-pi

    steps:
    - uses: actions/checkout@v3
    - run: dotnet publish Magic8HeadService/Magic8HeadService.csproj -c Release -o /srv/Magic8HeadService/
    - run: sudo systemctl restart Magic8HeadService
